### ISSUE TITLE
Need to be verified

### ISSUE THREAD

**Issue by caBBAlainB** [ker0x/CakeGCM#1]
Hello,

I think your plugin need to be verified. The controller try to call a sendNotification method which doesn't exists. Maybe sendToAll?

I think that you didn't upload your working version.

Regards
Alain

**Comment by ker0x** [comment]
Hello,

thanks for the report. I've refactored all the plugin. It should work correctly now.

**Comment by caBBAlainB** [comment]
Hi ker0x,
Thanks a lot, in fact I made it working on cakePHP 3.x.
